name = "dawn-eig-website"
compatibility_date = "2026-04-23"

[env.production]
  routes = [
    { pattern = "dawneig.com/*", zone_name = "dawneig.com" }
  ]

[[env.production.vars]]
  # Set via wrangler secret put CONTACT_EMAIL
  # Set via wrangler secret put RESEND_API_KEY
